version: '3.8'

services:
  # Agent Document Processing API (Primary)
  agent-orchestrator:
    build: .
    container_name: agent-orchestrator
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - DATABASE_URL=postgresql://agent_user:${POSTGRES_PASSWORD}@postgres:5432/agent_orchestration
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - agent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # PostgreSQL Database for document storage and analysis
  postgres:
    image: postgres:15
    container_name: agent-postgres
    environment:
      - POSTGRES_DB=agent_orchestration
      - POSTGRES_USER=agent_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    networks:
      - agent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U agent_user -d agent_orchestration"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: >
      postgres -c max_connections=200
               -c shared_buffers=256MB
               -c effective_cache_size=1GB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.9
               -c wal_buffers=16MB
               -c default_statistics_target=100
               -c random_page_cost=1.1
               -c effective_io_concurrency=200

  # Redis for caching and task queuing
  redis:
    image: redis:7-alpine
    container_name: agent-redis
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis_data:/data
    networks:
      - agent-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Cognee Development Memory Database (Goose conversational memory)
  cognee-dev-orchestrator:
    image: cognee/cognee:latest
    container_name: cognee-dev-orchestrator
    ports:
      - "8001:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - EMBEDDING_MODEL=gemini-embedding-001
      - COGNEE_ENV=development
    volumes:
      - scott_cognee_dev_data:/app/data
      - scott_cognee_dev_database:/app/database
      - scott_cognee_dev_logs:/app/logs
      - scott_cognee_dev_cache:/app/cache
      - ./config/cognee_mcp_robust.py:/tmp/cognee_mcp.py:ro
    networks:
      - agent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Cognee Business Intelligence Memory Database
  cognee-business-contracts:
    image: cognee/cognee:latest
    container_name: cognee-business-contracts
    ports:
      - "8002:8000"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - EMBEDDING_MODEL=gemini-embedding-001
      - COGNEE_ENV=business
    volumes:
      - scott_cognee_business_data:/app/data
      - scott_cognee_business_database:/app/database
      - scott_cognee_business_logs:/app/logs
      - scott_cognee_business_cache:/app/cache
      - ./config/cognee_mcp_robust.py:/tmp/cognee_mcp.py:ro
    networks:
      - agent-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8000/health', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  redis_data:
  # Cognee Memory Database Volumes
  scott_cognee_dev_data:
    external: true
  scott_cognee_dev_database:
    external: true
  scott_cognee_dev_logs:
    external: true
  scott_cognee_dev_cache:
    external: true
  scott_cognee_business_data:
    external: true
  scott_cognee_business_database:
    external: true
  scott_cognee_business_logs:
    external: true
  scott_cognee_business_cache:
    external: true

networks:
  agent-network:
    driver: bridge