GOOSE_MODEL: gemini-2.5-flash
OLLAMA_CONTEXT_LENGTH: 32768
OLLAMA_HOST: http://localhost:11434/
GOOSE_PROVIDER: google
extensions:
  agent_system:
    args: []
    bundled: null
    cmd: python
    cmdline: /home/scott/agent-project/config/agent_mcp_server.py
    description: Agent Document Processing System with LegalBERT
    enabled: true
    env_keys: []
    envs: {}
    name: Agent System
    timeout: 300
    type: stdio
  computercontroller:
    bundled: true
    description: null
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    description: null
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  memory:
    bundled: true
    description: null
    display_name: Memory
    enabled: true
    name: memory
    timeout: 300
    type: builtin
