GOOSE_MODEL: gemini-2.5-flash
OLLAMA_CONTEXT_LENGTH: 32768
OLLAMA_HOST: http://localhost:11434/
GOOSE_PROVIDER: google
extensions:
  router_agent:
    args: []
    bundled: null
    cmd: python3
    cmdline: /home/scott/agent-project/config/router_agent.py
    description: Intelligent Query Router - Routes between Cognee Memory and Agent API
    enabled: true
    env_keys: []
    envs: {}
    name: Router Agent
    timeout: 300
    type: stdio
  computercontroller:
    bundled: true
    description: null
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    description: null
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  memory:
    bundled: true
    description: null
    display_name: Memory
    enabled: true
    name: memory
    timeout: 300
    type: builtin
